# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-20 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='categories',
            new_name='category',
        ),
    ]
