# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-20 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20190220_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('cook_time', models.IntegerField(default=0)),
                ('categories', models.ManyToManyField(to='recipes.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='chef',
            name='fname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chef',
            name='lname',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Chef'),
        ),
    ]
