# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-20 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20190220_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
