# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-20 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20190220_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='photo',
            field=models.ImageField(default='{profile_pics/anon.png', upload_to='profile_pics'),
        ),
    ]
