# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-21 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20190220_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='supercat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='recipes.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('CAT', 'Category'), ('SUB', 'Subcategory')], default='CAT', max_length=25),
        ),
        migrations.AddField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, upload_to='food_pics'),
        ),
    ]
