# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-21 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20190221_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, upload_to='cat_pics'),
        ),
    ]
