# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-22 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='email',
            field=models.EmailField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='chef',
            name='fname',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='chef',
            name='lname',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='chef',
            name='username',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Chef'),
        ),
        migrations.AlterField(
            model_name='review',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
    ]
