# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-22 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_auto_20190222_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('CAT', 'Category'), ('SUB', 'Subcategory')], max_length=25),
        ),
        migrations.AlterField(
            model_name='chef',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='chef',
            name='fname',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='chef',
            name='lname',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='chef',
            name='username',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
    ]
