# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-22 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_auto_20190222_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='header',
            field=models.CharField(default='My Rating', max_length=50),
        ),
    ]
