# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-22 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_review_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='header',
            new_name='title',
        ),
    ]
