# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-22 15:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_review_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='email',
        ),
        migrations.RemoveField(
            model_name='chef',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='chef',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='chef',
            name='username',
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
