# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-28 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0029_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='comment',
            field=models.TextField(default=' I love this website!'),
        ),
    ]
