# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-01 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0031_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='photo',
            field=models.ImageField(default='anon.png', upload_to='profile_pics'),
        ),
    ]
