# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-01 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0032_auto_20190301_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, upload_to='cat_pics'),
        ),
    ]
