# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-13 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0035_auto_20190313_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='bio',
            field=models.TextField(default='Hello! I enjoy making food the opportunity to upload recipes, share tips, and explore recipes on this website!'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='comment',
            field=models.TextField(default='I love this website!'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='comment',
            field=models.TextField(default='I love this website!'),
        ),
    ]
