# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-13 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0036_auto_20190313_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='about',
            field=models.TextField(default='Check out my new recipe!'),
        ),
    ]
