# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0038_auto_20190318_1632'),
        ('recipes', '0038_auto_20190319_1201'),
    ]

    operations = [
    ]
